language: python

sudo: false

python:
  - 2.7

cache:
  directories:
    - $HOME/.cache/pip

addons:
  apt:
    packages:
      - libhdf5-serial-dev
      - python-dev
      - python-scipy
      - python-numpy
      - python-psycopg2
      - libopenblas-dev
      - liblapack-dev
      - gfortran

install:
  - pip install --upgrade pip
  - pip install -r requirements.txt

script:
  - nosetests --with-coverage

after_success:
  - coveralls
